<script type="text/javascript" src="fashion/js/jquery.min.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/jquery-ui.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/modernizr.js"></script>
    <script type="text/javascript" src="fashion/plugins/rev_slider/js/jquery.themepunch.revolution.min.js"></script>
    <script type="text/javascript" src="fashion/plugins/rev_slider/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="fashion/plugins/rev_slider/js/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="fashion/plugins/rev_slider/js/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="fashion/plugins/rev_slider/js/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="fashion/plugins/rev_slider/js/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/tether.min.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/bootstrap.min.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/owl.carousel.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/slick.js"></script>
    <script type="text/javascript" src="fashion/js/plugins/plugins-all.js"></script>
    <script type="text/javascript" src="fashion/js/custom.js"></script>